---
title: "CV summary"
output: 
  html_document:
    theme: united
  
---
<style>
body {
text-align: justify}
</style>


## Overview
I am a postdoctoral researcher at Biodiversity Research Institute (IMIB). I obtained in December 2021 the PhD degree in Agricultural and Environmental Sciences (cum laude). I also hold an MSc in Applied Research in Wildlife and Game Resources (2017) and a BSc in Environmental Sciences (2016). I have published 32 peer-reviewed publications (25 of them Q1, 12 as first/corresponding aurthor), and 12 scientific reports. I have lectured for 215 hours at the Bsc and Master level. I have also **supervised 11 bachelor/master students, hosted one PhD student, and one postdoctoral** researchers, and co-supervised chapters of four PhD thesis. I have received **292,655.70€** in competitive calls as principal investigator (PI)/beneficiary. I have been PI of four projects calls, and I have collaborated as a researcher on seven projects and 10 transfer of knowledge contracts. I have contributed with **47 presentations at national/international congresses**. Regarding international mobility, I have been funded in competitive calls to visit four universities and research institutions abroad for a total period of 33 months (9 pre-doc + 24 post-doc) at the Zoological Society of London (UK), Uni. of St. Andrews (UK), Uni. of Agricultural Sciences (Sweden) and Uni. of Torino (Italy). **I have published articles with 112 international researchers**. I am associate editor of the journal Ecosystems edited by the Spanish Association of Terrestrial Ecology, and I have served on the evaluation committee for one competitive project call. I have been a member of the organizing committee of two scientific congresses, and one of the scientific committees. I am also a **member of the European Observatory of Wildlife (EOW) advisory board**, a European network capable of monitoring wildlife populations. I give particular attention to communicating and disseminating research, interacting frequently with the media (e.g. El País) and managing an X account [@cameratraps1](https://x.com/cameratraps1) with > 2,1K followers in which I disseminate information about wildlife, camera traps and research. I usually transfer my knowledge to the international and national levels in the form of courses and workshops. For instance, I have been invited as a keynote speaker to seminars organized by Imperial College of London, veterinarians and engineering associations, and workshops hosted by ENETWILD project, Mammalnet CitSci project and Palombar NGO. I have received the “Seal of Excellence” in my project proposal “One health: tick-borne pathogens in the context of a wildlife pandemic” in Marie Skłodowska-Curie Actions Postdoctoral Fellowships 2022 (MSCA-PF). I have been also awarded extraordinary prices on the Bachelor, Master and PhD levels. 
<br/><br/>

## TOP-10 publications
1. **Palencia**, P., Sereno Cadierno, J., Carniato, D., Marques, T., Hofmeester, T. R., Vicente, J., & Acevedo, P. (2024). [Clustered and rotating designs as a strategy to obtain precise detection rates in camera trapping studies](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.14690). *Journal of Applied Ecology*. 
	
2. Zampetti, A., Mirante, D., **Palencia, P.**, & Santini, L. (2024). [Towards an automated protocol for wildlife density estimation using camera‐traps](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.14450) *Methods in Ecology and Evolution*. 
	
3. **Palencia, P.**, & Barroso, P. (2024). [Disentangling ground-nest predation rates through an artificial nests experiment in an area with western capercaillie (Tetrao urogallus) presence: martens are the key](https://link.springer.com/article/10.1007/s10344-024-01837-9). *European Journal of Wildlife Research*, 70(5), 87. 
	
4. Delisle, Z. J., Henrich, M., **Palencia, P.**, & Swihart, R. K. (2023). [Reducing bias in density estimates for unmarked populations that exhibit reactive behaviour towards camera traps](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.14247) *Methods in Ecology and Evolution*, 14(12), 3100-3111. 
	
5. **Palencia, P.**, Vada, R., Zanet, S., Calvini, M., Gola, G., & Ferroglio, E. (2023). [Not just pictures: Utility of camera trapping in the context of African swine fever and wild boar management](https://onlinelibrary.wiley.com/doi/full/10.1155/2023/7820538?msockid=198d1e9a20b862c23d1d0b8b2110631c). *Transboundary and Emerging Diseases*, 2023(1), 7820538. AC: Palencia, P. 
	
6. Barroso, P., Relimpio, D., Zearra, J. A., Cerón, J. J., **Palencia, P.** Cardoso, B., ... & Gortázar, C. (2023). [Using integrated wildlife monitoring to prevent future pandemics through one health approach](https://www.sciencedirect.com/science/article/pii/S2352771422001112) *One Health*, 16, 100479. 
	
7. **Palencia, P.**, Barroso, P., Vicente, J., Hofmeester, T. R., Ferreres, J., & Acevedo, P. (2022). [Random encounter model is a reliable method for estimating population density of multiple species using camera traps](https://zslpublications.onlinelibrary.wiley.com/doi/full/10.1002/rse2.269) *Remote Sensing in Ecology and Conservation*, 8(5), 670-682. 
	
8. **Palencia, P.**, Vicente, J., Soriguer, R. C., & Acevedo, P. (2022). [Towards a best practices guide for camera trapping: assessing differences among camera trap models and settings under field conditions](https://zslpublications.onlinelibrary.wiley.com/doi/full/10.1111/jzo.12945) *Journal of Zoology*, 316(3), 197-208.  
	
9. **Palencia, P.**, Rowcliffe, J. M., Vicente, J., & Acevedo, P. (2021). [Assessing the camera trap methodologies used to estimate density of unmarked populations](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2664.13913) *Journal of Applied Ecology*, 58(8), 1583-1592. 
	
10. Palencia, P., Fernández López, J., Vicente, J., & Acevedo, P. (2021). [Innovations in movement and behavioural ecology from camera traps: Day range as model parameter](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13609) *Methods in Ecology and Evolution*, 12(7), 1201-1212.


## TOP-10 congress communications
1. Oral communication – international congress: **P. Palencia**, López-Bao, J. V.; Barroso, P.; Gallardo, H.; Jaumejoan, X.; Sazatornil, V. & Mateo-Tomás, P. Low wild boar predation rates in artificial ground nests in capercaillie habitats *9th World Conference on Mountain Ungulates, Dushanbe*, Tajikistan, 12/10/2024-15/10/2024
	
2. Oral communication – international congress: **P. Palencia**, P. Acevedo, T. R. Hofmeester, J. Sereno, & J. Vicente. Disentangling the drivers of wild boar movement patterns from camera trap data. *13th Symposium on Wild Boar and Other Suids*, Barcelona, Spain, 6/9/2022-/9/2022
	
3. Poster communication – international congress: **P Palencia**, S Blome, E Ferroglio, A Gogin, Y Jo, R, A Linden, M-L Penrith, J Vicente, A Viltrop & C Gortazar. Tools and opportunities for African swine fever control in wild boar and feral pigs: a review. *13th Symposium on Wild Boar and Other Suids*, Barcelona, Spain, 6/9/2022-9/9/2022
	
4. Oral communication – national congress: **P. Palencia**, J. Vicente & P. Acevedo. Avances en la monitorización de densidad poblacional y ecología del movimiento de mamíferos no reconocibles (unmarked species) mediante fototrampeo. *XV Congreso de la Sociedad Española para la Conservación y Estudio de los Mamíferos (SECEM)*; Córdoba, Spain; 04-07/12/2021
	
5. Poster communication – international congress: **P. Palencia**, J. Fernández-López, J. Vicente & P. Acevedo. Innovations in movement and behavioural ecology from camera traps: day range as model parameter. *Scaling Up Camera Trap Surveys to Inform Regional Wildlife Conservation*. Canadá; 18/05/2020
	
6. Oral communication – international congress: **P. Palencia**, F. Carro, R. C. Soriguer, J. Vicente & P. Acevedo. Considerations for analyzing a long time series of distance sampling data. *IX Meeting of Iberian Wild Ungulates*. Granada, Spain; 04-06/10/2018
	
7. Poster communication – international congress: **P. Palencia**, P. Iglesias, J. Jiménez, F. Carro, R. C. Soriguer, J. Vicente & P. Acevedo. Assessing the random encounter model reliability with wild ungulates. *12th Symposium on Wild Boar and Other Suids*. Lázne, Czech Republic; 04-07/09/2018
	
8. Poster communication – international congress: **P. Palencia**, B. Bovillo, J. Vicente, X. Pardavila, L. Royo, F. Carro, A. Lamosa & P. Acevedo. Seasonal and spatial variation in wild boar movement behaviour: implications for random encounter model. *12th Symposium on Wild Boar and Other Suids*. Lázne, Czech Republic; 04-07/09/2018
	
9. Oral communication – national congress: **P. Palencia**, P. Barroso, J. Vicente & P. Acevedo. Efecto de la tortuosidad sobre estimas del rango diario de desplazamiento: el jabalí (Sus scrofa) como caso de estudio. *XIII Congreso de la Sociedad Española para la Conservación y Estudio de los Mamíferos (SECEM)*. Guadalajara, Spain; 06-09/12/2017
	
10. Poster communication – international congress: **P. Palencia, P**. Barroso, J. Vicente & P. Acevedo. Estimating wild boar (Sus scrofa) travel speed and day range: is telemetry the more precise option? *Trends in Biodiversity and Evolution (TiBE)*. Vairão, Portugal; 28-30/06/2017

<br/><br/>

