---
title: "Research"
output: 
  html_document:
    theme: united
  
---

# **Narrative description**
My research is focused on developing and fine-tuning cutting-edge tools for wildlife management and conservation. I could highlight three research lines. **Line-1**: new methodologies for population size estimation: I started to work in this research line during my master's thesis. I have made a key contribution to developing and harmonising methods capable of providing reliable population size estimates for populations in which traditional methods are not useful (e.g. when monitoring low-detectable and/or non-recognisable species). Particularly, I am focused on using remotely activated cameras (camera traps), and the random encounter model (a method that does not require individually identifying animals to estimate population density, REM), both having a multi-species utility. I have also a strong background in traditional methods such as distance sampling and spatially explicit capture-recapture. Advances derived from this line have established REM as a reliable multi-species method used in several conservation programs. **Line-2**: health-surveillance under one-health perspective: I did my PhD in a “health and biotechnology group”, and my first postdoc in a Veterinary Faculty. Thus, considering my quantitative ecologist profile, I have participated in integrated wildlife monitoring studies. Integrated wildlife monitoring merges wildlife health and host community monitoring for effective disease management and prevention. I have led the host community monitoring, working with shared diseases between wildlife and livestock such as African swine fever (ASF), bovine tuberculosis, sarcoptic mange, toxoplasma gondii or bluetongue among others. All this demonstrates my interdisciplinary. Special mention requires ASF, a virus causing 90% mortality in wild boar and pigs. I dedicated my first postdoc at the University of Turin to design, implement (in collaboration with Italian authorities) and fine-tuning an integrated wildlife monitoring program to monitor the spread of the virus in the infected populations of Italy. Finally, **Line-3**: innovative tools for conservation: this is the most recent research line, which started during my postdoc period at the Biodiversity Research Institute (IMIB). I am focused on addressing conservation problems by using non-lethal and cost-efficient alternatives. Particularly, I am focused on the impact of predators on the decline of ground-nesting birds, and diversionary feeding (deliberate provisioning of food to explore the propensity of individuals to exploit the most easily accessed resource) as a non-lethal tool.
<br/>
<br/>

# **Projects**
More coming soon!

## **Impact of diversionary feeding at population level**
<br/>

## **Utility of diversionary feeding on reducing predators impact on ground-nesting birds**
<br/>

## **Survey design**
<br/>

## **African swine fever emergence**
<br/>

## **Density estimation & unmarked populations**
<br/>

## **Camera trapping & movement ecology**
<br/>